from __future__ import annotations

import argparse
import contextlib
import importlib.util
import json
import os
import re
import secrets
import stat
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any, NoReturn, cast

from careerops.evaluation import (
    REPORT_VERSION,
    RULE_SET_SHA256,
    RULE_SET_VERSION,
    SCAN_SCOPE,
    TOOL_NAME,
    TOOL_VERSION,
)

JsonObject = dict[str, Any]
FileSignature = tuple[int, int, int, int, int]

PLAN_PATH = Path("datasets/manifests/d0-pilot-plan.json")
SPLITS = ("development", "validation", "holdout")
INCOMPLETE_MARKER = "INCOMPLETE SKELETON - not evidence; fill with independently reviewed real data"
DATASET_ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")
FROZEN_DATASET_IDS = frozenset(
    {
        "calendar",
        "contact",
        "dedup",
        "discovery_parser",
        "email",
        "evidence_match",
        "policy_injection",
        "reconciliation",
        "remote",
    }
)
KNOWN_PLAN_STATUSES = frozenset({"completed", "planned"})
MAX_JSON_BYTES = 8 * 1024 * 1024
MAX_ARTIFACT_BYTES = 64 * 1024 * 1024
MAX_ARTIFACT_ROWS = 10_000


class D0ArgumentParser(argparse.ArgumentParser):
    def error(self, message: str) -> NoReturn:
        if "--json" in sys.argv:
            payload: JsonObject = {
                "scope": "d0_intake",
                "passed": False,
                "errors": ["invalid arguments"],
            }
            print(_stable_json(payload), file=sys.stderr)
            raise SystemExit(2)
        super().error(message)


@dataclass(frozen=True, slots=True)
class CommandResult:
    exit_code: int
    payload: JsonObject


@dataclass(frozen=True, slots=True)
class ScaffoldWrite:
    directory_fd: int
    relative: Path
    content: JsonObject
    signature: FileSignature | None


def main(argv: Sequence[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    handler = cast(Callable[[argparse.Namespace], CommandResult], args.handler)
    result = handler(args)
    _emit(result.payload, json_output=bool(getattr(args, "json", False)))
    return result.exit_code


def _parser() -> argparse.ArgumentParser:
    parser = D0ArgumentParser(
        prog="careerops-d0",
        description="Safe D0 intake evidence status, scaffolding, and validation.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="repository root containing datasets/ and docs/ (default: current directory)",
    )
    subcommands = parser.add_subparsers(required=True, parser_class=D0ArgumentParser)

    status = subcommands.add_parser("status", help="derive D0 intake status from plan/evidence")
    status.add_argument("--json", action="store_true", help="emit deterministic JSON")
    status.set_defaults(handler=_status)

    scaffold = subcommands.add_parser(
        "scaffold",
        help="create incomplete D0 evidence skeleton files without overwriting by default",
    )
    scaffold.add_argument(
        "--dataset",
        required=True,
        action="append",
        dest="datasets",
        help="dataset ID to scaffold; may be repeated",
    )
    scaffold.add_argument(
        "--force",
        action="store_true",
        help="overwrite only exact, untouched skeletons generated by this CLI",
    )
    scaffold.add_argument("--json", action="store_true", help="emit deterministic JSON")
    scaffold.set_defaults(handler=_scaffold)

    validate = subcommands.add_parser("validate", help="validate D0 evidence")
    validate.add_argument(
        "--contracts-only",
        action="store_true",
        help="validate static contracts only; does not claim pilot evidence completion",
    )
    validate.add_argument("--json", action="store_true", help="emit deterministic JSON")
    validate.set_defaults(handler=_validate)

    return parser


def _status(args: argparse.Namespace) -> CommandResult:
    root = _repo_root(args.root)
    errors: list[str] = []
    plan = _read_json_object(root / PLAN_PATH, errors, "pilot plan")
    datasets = _plan_datasets(plan, errors)

    required_total = 0
    declared_actual_total = 0
    derived_actual_total = 0
    manifest_references = 0
    manifest_files_present = 0
    scan_reports_present = 0
    scan_reports_zero_unsuppressed = 0
    datasets_satisfied = 0
    dataset_status: list[JsonObject] = []

    for dataset in datasets:
        dataset_id = _safe_dataset_id(dataset.get("id"))
        required = _non_negative_int(dataset.get("pilot_required"))
        declared_actual = _non_negative_int(dataset.get("pilot_actual"))
        required_total += required or 0
        declared_actual_total += declared_actual or 0

        manifest_value = dataset.get("manifest")
        manifest_path: Path | None = None
        manifest_error: str | None = None
        derived_counts = _empty_counts()
        scan_status: JsonObject = {"present": False, "zero_unsuppressed_findings": False}

        if isinstance(manifest_value, str) and manifest_value.strip():
            manifest_references += 1
            manifest_path = _safe_repo_path(root, manifest_value)
            if manifest_path is None:
                manifest_error = "manifest path escapes repository"
            elif manifest_path.is_file():
                manifest_files_present += 1
                manifest_errors: list[str] = []
                manifest = _read_json_object(
                    manifest_path,
                    manifest_errors,
                    f"{dataset_id} manifest",
                )
                artifact = manifest.get("artifact")
                if isinstance(artifact, dict):
                    artifact_path = _safe_repo_path(
                        root,
                        cast(dict[str, Any], artifact).get("path"),
                    )
                    if artifact_path is None:
                        manifest_error = "artifact path missing or unsafe"
                    elif artifact_path.is_file():
                        rows = _read_artifact_rows(artifact_path, manifest_errors, dataset_id)
                        derived_counts = _count_rows(rows)
                    else:
                        manifest_error = "artifact file missing"
                scan = manifest.get("pii_scan")
                scan_status = _scan_status(root, scan, manifest_errors)
                if scan_status["present"]:
                    scan_reports_present += 1
                if scan_status["zero_unsuppressed_findings"]:
                    scan_reports_zero_unsuppressed += 1
                if manifest_errors and manifest_error is None:
                    manifest_error = "; ".join(manifest_errors[:3])
            else:
                manifest_error = "manifest file missing"

        real_count = cast(int, derived_counts["real_count"])
        derived_actual_total += real_count
        if required is not None and real_count >= required:
            datasets_satisfied += 1
        dataset_status.append(
            {
                "id": dataset_id,
                "pilot_required": required,
                "pilot_actual_declared": declared_actual,
                "pilot_actual_derived": real_count,
                "manifest_present": manifest_path is not None and manifest_path.is_file(),
                "scan": scan_status,
                "error": manifest_error,
            }
        )

    roles = plan.get("roles")
    quality = plan.get("quality")
    declared_scan_pass = (
        cast(JsonObject, quality).get("pii_scan_passed") if isinstance(quality, dict) else None
    )
    derived_zero_finding_reports = bool(datasets) and scan_reports_zero_unsuppressed == len(
        datasets
    )
    payload: JsonObject = {
        "scope": "d0_intake",
        "plan": str(PLAN_PATH),
        "plan_status_declared": _safe_plan_status(plan.get("status")),
        "release_qualification_authorized": False,
        "roles": {
            "data_curator_assigned": _assigned_role(roles, "data_curator"),
            "independent_reviewer_assigned": _assigned_role(roles, "independent_reviewer"),
            "adjudicator_assigned": _assigned_role(roles, "adjudicator"),
        },
        "quality": {
            "pii_scan_passed_declared": (
                declared_scan_pass if isinstance(declared_scan_pass, bool) else None
            ),
            "technical_scan_zero_findings_derived_from_report": derived_zero_finding_reports,
        },
        "counts": {
            "dataset_count": len(datasets),
            "manifest_references": manifest_references,
            "manifest_files_present": manifest_files_present,
            "scan_reports_present": scan_reports_present,
            "scan_reports_zero_unsuppressed": scan_reports_zero_unsuppressed,
            "pilot_rows_required": required_total,
            "pilot_rows_declared_actual": declared_actual_total,
            "pilot_rows_derived_actual": derived_actual_total,
            "datasets_satisfied_by_derived_rows": datasets_satisfied,
        },
        "datasets": dataset_status,
        "errors": errors,
    }
    return CommandResult(1 if errors else 0, payload)


def _scaffold(args: argparse.Namespace) -> CommandResult:
    root = _repo_root(args.root)
    errors: list[str] = []
    plan = _read_json_object(root / PLAN_PATH, errors, "pilot plan")
    datasets = _plan_datasets(plan, errors)
    known = {
        dataset_id
        for dataset in datasets
        if (dataset_id := _safe_dataset_id_or_none(dataset.get("id"))) is not None
    }
    requested: set[str] = set()
    for index, requested_id in enumerate(cast(list[str], args.datasets or [])):
        if requested_id not in known or not _valid_dataset_id(requested_id):
            errors.append(f"unknown dataset selection at index {index}")
        else:
            requested.add(requested_id)
    datasets = [dataset for dataset in datasets if dataset.get("id") in requested]

    created: list[str] = []
    skipped: list[str] = []
    writes: list[ScaffoldWrite] = []
    directory_fds: list[int] = []
    try:
        if not errors:
            for dataset_index, dataset in enumerate(datasets):
                dataset_id = _safe_dataset_id(dataset.get("id"))
                if not _valid_dataset_id(dataset_id):
                    continue
                directory_fd = _open_scaffold_directory(root, dataset_id)
                if directory_fd is None:
                    errors.append(f"unsafe scaffold path for dataset index {dataset_index}")
                    continue
                directory_fds.append(directory_fd)
                for relative, content in _skeletons_for(dataset).items():
                    exists, signature = _inspect_skeleton_at(
                        directory_fd,
                        relative.name,
                        content,
                    )
                    if exists and not args.force:
                        skipped.append(str(relative))
                        continue
                    if exists and signature is None:
                        errors.append(f"refusing to overwrite non-skeleton file: {relative}")
                        continue
                    writes.append(
                        ScaffoldWrite(
                            directory_fd=directory_fd,
                            relative=relative,
                            content=content,
                            signature=signature,
                        )
                    )

        # Force mode is fail-closed: every target must pass inspection before any replacement.
        if not errors:
            for write in writes:
                write_error = _atomic_write_skeleton(write)
                if write_error is not None:
                    errors.append(f"{write_error}: {write.relative}")
                    break
                created.append(str(write.relative))
    finally:
        for directory_fd in directory_fds:
            with contextlib.suppress(OSError):
                os.close(directory_fd)

    payload: JsonObject = {
        "scope": "d0_intake",
        "created": sorted(created),
        "skipped_existing": sorted(skipped),
        "errors": errors,
        "note": (
            "Scaffolded files are explicitly incomplete and are not referenced by the pilot plan."
        ),
    }
    return CommandResult(1 if errors else 0, payload)


def _validate(args: argparse.Namespace) -> CommandResult:
    root = _repo_root(args.root)
    errors: list[str] = []
    details: JsonObject = {}
    try:
        verifier = _load_verify_m1()
    except (ImportError, OSError, AttributeError, SyntaxError, ValueError) as exc:
        errors.append(f"unable to load verifier: {type(exc).__name__}")
    else:
        try:
            contract_errors, contract_details = verifier.verify_contracts(root)
            errors.extend(str(error) for error in contract_errors)
            details.update(cast(dict[str, Any], contract_details))
            if not args.contracts_only:
                pilot_errors, pilot_details = verifier.verify_full_pilot(root)
                errors.extend(str(error) for error in pilot_errors)
                details.update(cast(dict[str, Any], pilot_details))
        except Exception as exc:  # verifier is script-local; fail closed.
            errors.append(f"verifier failed: {type(exc).__name__}")

    payload: JsonObject = {
        "scope": "d0_intake",
        "mode": "contracts_only" if args.contracts_only else "full",
        "passed": not errors,
        "release_qualification_authorized": False,
        "details": details,
        "errors": errors,
    }
    return CommandResult(0 if not errors else 1, payload)


def _load_verify_m1() -> ModuleType:
    module_path = Path(__file__).resolve()
    package_root = module_path.parents[1]
    source_root = module_path.parents[3]
    candidates = (
        (package_root, package_root / "_trusted" / "verify_m1.py"),
        (source_root, source_root / "scripts" / "verify_m1.py"),
    )
    script: Path | None = None
    for anchor, candidate in candidates:
        try:
            resolved_anchor = anchor.resolve(strict=True)
            resolved_candidate = candidate.resolve(strict=True)
            resolved_candidate.relative_to(resolved_anchor)
        except (FileNotFoundError, OSError, ValueError):
            continue
        if resolved_candidate.is_file():
            script = resolved_candidate
            break
    if script is None:
        raise FileNotFoundError("trusted verify_m1.py is unavailable")
    spec = importlib.util.spec_from_file_location("careerops_d0_verify_m1", script)
    if spec is None or spec.loader is None:
        raise ImportError("scripts/verify_m1.py cannot be imported")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    for name in ("verify_contracts", "verify_full_pilot"):
        if not callable(getattr(module, name, None)):
            raise AttributeError(f"missing verifier function: {name}")
    return module


def _skeletons_for(dataset: JsonObject) -> dict[Path, JsonObject]:
    dataset_id = _safe_dataset_id(dataset.get("id"))
    schema = f"datasets/schemas/{dataset_id}.schema.json"
    guide = f"datasets/labeling-guides/{dataset_id}.md"
    zero_hash = "0" * 64
    base = f"datasets/d0-intake/{dataset_id}"
    return {
        Path(f"{base}/source-manifest.incomplete.json"): {
            "incomplete": True,
            "marker": INCOMPLETE_MARKER,
            "dataset_id": dataset_id,
            "source_items": [],
        },
        Path(f"{base}/artifact.incomplete.json"): {
            "incomplete": True,
            "marker": INCOMPLETE_MARKER,
            "rows": [],
        },
        Path(f"{base}/label-review.incomplete.json"): {
            "incomplete": True,
            "marker": INCOMPLETE_MARKER,
            "rows": [],
        },
        Path(f"{base}/scan-report.incomplete.json"): {
            "incomplete": True,
            "marker": INCOMPLETE_MARKER,
            "version": REPORT_VERSION,
            "scan_scope": SCAN_SCOPE,
            "dataset_id": dataset_id,
            "dataset_version": "INCOMPLETE",
            "artifact_sha256": zero_hash,
            "tool": TOOL_NAME,
            "tool_version": TOOL_VERSION,
            "rule_set_version": RULE_SET_VERSION,
            "rule_set_sha256": RULE_SET_SHA256,
            "scanned_at": "1970-01-01T00:00:00Z",
            "unsuppressed_findings_count": 0,
            "unsuppressed_findings": [],
            "reviewed_suppressions": [],
        },
        Path(f"{base}/manifest.incomplete.json"): {
            "incomplete": True,
            "marker": INCOMPLETE_MARKER,
            "version": 1,
            "dataset_id": dataset_id,
            "dataset_version": "INCOMPLETE",
            "schema": schema,
            "guide": guide,
            "source": {
                "source_manifest": f"{base}/source-manifest.incomplete.json",
                "source_manifest_sha256": zero_hash,
                "consent_ref": f"{base}/consent.incomplete.json",
                "consent_sha256": zero_hash,
                "retention_ref": f"{base}/retention.incomplete.json",
                "retention_sha256": zero_hash,
            },
            "artifact": {
                "path": f"{base}/artifact.incomplete.json",
                "sha256": zero_hash,
                "row_count": 0,
                "real_count": 0,
                "synthetic_count": 0,
            },
            "splits": {split: 0 for split in SPLITS},
            "groups": {
                "total_count": 0,
                "split_counts": {split: 0 for split in SPLITS},
            },
            "labels": {
                "implementer": "INCOMPLETE",
                "independent_reviewer": "INCOMPLETE",
                "adjudicator": "INCOMPLETE",
                "review": {
                    "path": f"{base}/label-review.incomplete.json",
                    "sha256": zero_hash,
                },
                "double_labeled_count": 0,
                "categorical_kappa": 0,
                "structured_exact_agreement": 0,
                "adjudication_complete": False,
            },
            "pii_scan": {
                "path": f"{base}/scan-report.incomplete.json",
                "sha256": zero_hash,
            },
        },
        Path(f"{base}/consent.incomplete.json"): {
            "incomplete": True,
            "marker": INCOMPLETE_MARKER,
            "dataset_id": dataset_id,
            "consent_evidence": [],
        },
        Path(f"{base}/retention.incomplete.json"): {
            "incomplete": True,
            "marker": INCOMPLETE_MARKER,
            "dataset_id": dataset_id,
            "retention_evidence": [],
        },
    }


def _repo_root(value: Path) -> Path:
    return value.expanduser().resolve()


def _read_json_object(path: Path, errors: list[str], label: str) -> JsonObject:
    payload = _read_bounded_bytes(path, MAX_JSON_BYTES, errors, label)
    if payload is None:
        return {}
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError:
        errors.append(f"{label} must be UTF-8")
        return {}
    try:
        parsed = json.loads(
            text,
            parse_constant=_reject_non_finite_json,
            object_pairs_hook=_reject_duplicate_json_keys,
        )
    except (json.JSONDecodeError, ValueError, RecursionError) as exc:
        errors.append(f"{label} is invalid JSON: {exc}")
        return {}
    if not isinstance(parsed, dict):
        errors.append(f"{label} must be a JSON object")
        return {}
    return cast(JsonObject, parsed)


def _read_artifact_rows(path: Path, errors: list[str], dataset_id: str) -> list[JsonObject]:
    payload = _read_bounded_bytes(path, MAX_ARTIFACT_BYTES, errors, f"{dataset_id}: artifact")
    if payload is None:
        return []
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError:
        errors.append(f"{dataset_id}: artifact must be UTF-8")
        return []
    stripped = text.strip()
    if not stripped:
        return []
    raw_rows: list[Any] = []
    try:
        parsed = json.loads(
            stripped,
            parse_constant=_reject_non_finite_json,
            object_pairs_hook=_reject_duplicate_json_keys,
        )
    except (json.JSONDecodeError, ValueError, RecursionError):
        for line_number, line in enumerate(text.splitlines(), start=1):
            if not line.strip():
                continue
            if len(raw_rows) >= MAX_ARTIFACT_ROWS:
                errors.append(f"{dataset_id}: artifact exceeds row limit")
                return []
            try:
                raw_rows.append(
                    json.loads(
                        line,
                        parse_constant=_reject_non_finite_json,
                        object_pairs_hook=_reject_duplicate_json_keys,
                    )
                )
            except (json.JSONDecodeError, ValueError, RecursionError) as exc:
                errors.append(f"{dataset_id}: invalid JSONL artifact line {line_number}: {exc}")
                return []
    else:
        raw_rows = cast(list[Any], parsed) if isinstance(parsed, list) else [parsed]
    if len(raw_rows) > MAX_ARTIFACT_ROWS:
        errors.append(f"{dataset_id}: artifact exceeds row limit")
        return []
    rows: list[JsonObject] = []
    for index, row in enumerate(raw_rows):
        if isinstance(row, dict):
            rows.append(cast(JsonObject, row))
        else:
            errors.append(f"{dataset_id}: artifact row {index + 1} must be an object")
    return rows


def _plan_datasets(plan: JsonObject, errors: list[str]) -> list[JsonObject]:
    raw = plan.get("datasets")
    if not isinstance(raw, list):
        errors.append("pilot plan datasets must be an array")
        return []
    datasets: list[JsonObject] = []
    for index, item in enumerate(cast(list[Any], raw)):
        if isinstance(item, dict):
            dataset = cast(JsonObject, item)
            if _safe_dataset_id_or_none(dataset.get("id")) is None:
                errors.append(f"pilot plan dataset {index} has invalid id")
            datasets.append(dataset)
        else:
            errors.append(f"pilot plan dataset {index} must be an object")
    return datasets


def _scan_status(root: Path, scan: Any, errors: list[str]) -> JsonObject:
    status: JsonObject = {"present": False, "zero_unsuppressed_findings": False}
    if not isinstance(scan, dict):
        return status
    path = _safe_repo_path(root, cast(dict[str, Any], scan).get("path"))
    if path is None or not path.is_file():
        return status
    status["present"] = True
    report = _read_json_object(path, errors, "scan report")
    findings = report.get("unsuppressed_findings")
    count = report.get("unsuppressed_findings_count")
    status["zero_unsuppressed_findings"] = findings == [] and count == 0
    return status


def _count_rows(rows: list[JsonObject]) -> JsonObject:
    counts = _empty_counts()
    groups: dict[str, set[str]] = {split: set() for split in SPLITS}
    for row in rows:
        split = row.get("split")
        if split in SPLITS:
            cast(dict[str, int], counts["split_counts"])[cast(str, split)] += 1
            group_id = row.get("group_id")
            if isinstance(group_id, str):
                groups[cast(str, split)].add(group_id)
        if row.get("synthetic") is True:
            counts["synthetic_count"] = cast(int, counts["synthetic_count"]) + 1
        elif row.get("synthetic") is False:
            counts["real_count"] = cast(int, counts["real_count"]) + 1
    counts["row_count"] = len(rows)
    counts["group_count"] = len(
        {group for split_groups in groups.values() for group in split_groups}
    )
    counts["group_split_counts"] = {split: len(groups[split]) for split in SPLITS}
    return counts


def _empty_counts() -> JsonObject:
    return {
        "row_count": 0,
        "real_count": 0,
        "synthetic_count": 0,
        "split_counts": {split: 0 for split in SPLITS},
        "group_count": 0,
        "group_split_counts": {split: 0 for split in SPLITS},
    }


def _assigned_role(roles: Any, key: str) -> bool:
    if not isinstance(roles, dict):
        return False
    value = cast(dict[str, Any], roles).get(key)
    return isinstance(value, str) and bool(value.strip())


def _safe_repo_path(root: Path, value: Any) -> Path | None:
    if not isinstance(value, str) or not value.strip():
        return None
    candidate = Path(value)
    if candidate.is_absolute():
        return None
    try:
        resolved = (root / candidate).resolve()
        resolved.relative_to(root)
    except (OSError, ValueError):
        return None
    return resolved


def _open_scaffold_directory(root: Path, dataset_id: str) -> int | None:
    if not _valid_dataset_id(dataset_id):
        return None
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
    descriptors: list[int] = []
    try:
        root_fd = os.open(root, flags)
        descriptors.append(root_fd)
        datasets_fd = _open_directory_at(root_fd, "datasets", flags=flags, create=False)
        if datasets_fd is None:
            return None
        descriptors.append(datasets_fd)
        intake_fd = _open_directory_at(datasets_fd, "d0-intake", flags=flags, create=True)
        if intake_fd is None:
            return None
        descriptors.append(intake_fd)
        dataset_fd = _open_directory_at(intake_fd, dataset_id, flags=flags, create=True)
        if dataset_fd is None:
            return None
        return dataset_fd
    except OSError:
        return None
    finally:
        for descriptor in reversed(descriptors):
            with contextlib.suppress(OSError):
                os.close(descriptor)


def _open_directory_at(
    parent_fd: int,
    name: str,
    *,
    flags: int,
    create: bool,
) -> int | None:
    try:
        return os.open(name, flags, dir_fd=parent_fd)
    except FileNotFoundError:
        if not create:
            return None
    except OSError:
        return None
    try:
        os.mkdir(name, mode=0o700, dir_fd=parent_fd)
    except FileExistsError:
        pass
    except OSError:
        return None
    try:
        return os.open(name, flags, dir_fd=parent_fd)
    except OSError:
        return None


def _inspect_skeleton_at(
    directory_fd: int,
    name: str,
    expected: JsonObject,
) -> tuple[bool, FileSignature | None]:
    if Path(name).name != name:
        return True, None
    flags = os.O_RDONLY | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
    try:
        descriptor = os.open(name, flags, dir_fd=directory_fd)
    except FileNotFoundError:
        return False, None
    except OSError:
        return True, None
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode):
            return True, None
        payload = bytearray()
        while len(payload) <= MAX_JSON_BYTES:
            chunk = os.read(descriptor, min(1024 * 1024, MAX_JSON_BYTES + 1 - len(payload)))
            if not chunk:
                break
            payload.extend(chunk)
        after = os.fstat(descriptor)
    except OSError:
        return True, None
    finally:
        with contextlib.suppress(OSError):
            os.close(descriptor)
    before_signature = _file_signature(before)
    if before_signature != _file_signature(after):
        return True, None
    if bytes(payload) != _skeleton_bytes(expected):
        return True, None
    return True, before_signature


def _file_signature(value: os.stat_result) -> FileSignature:
    return (value.st_dev, value.st_ino, value.st_size, value.st_mtime_ns, value.st_ctime_ns)


def _skeleton_bytes(content: JsonObject) -> bytes:
    return (_stable_json(content) + "\n").encode("utf-8")


def _atomic_write_skeleton(write: ScaffoldWrite) -> str | None:
    temporary_name: str | None = None
    descriptor = -1
    try:
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
        for _attempt in range(8):
            candidate = f".{write.relative.name}.{secrets.token_hex(8)}.tmp"
            try:
                descriptor = os.open(
                    candidate,
                    flags,
                    0o600,
                    dir_fd=write.directory_fd,
                )
            except FileExistsError:
                continue
            temporary_name = candidate
            break
        if temporary_name is None:
            return "unable to allocate scaffold temporary file"
        with os.fdopen(descriptor, "wb") as file:
            descriptor = -1
            file.write(_skeleton_bytes(write.content))
            file.flush()
            os.fsync(file.fileno())
        if write.signature is None:
            os.link(
                temporary_name,
                write.relative.name,
                src_dir_fd=write.directory_fd,
                dst_dir_fd=write.directory_fd,
                follow_symlinks=False,
            )
        else:
            exists, current_signature = _inspect_skeleton_at(
                write.directory_fd,
                write.relative.name,
                write.content,
            )
            if not exists or current_signature != write.signature:
                return "scaffold target changed after preflight"
            os.replace(
                temporary_name,
                write.relative.name,
                src_dir_fd=write.directory_fd,
                dst_dir_fd=write.directory_fd,
            )
            temporary_name = None
        with contextlib.suppress(OSError):
            os.fsync(write.directory_fd)
    except FileExistsError:
        return "scaffold target changed after preflight"
    except OSError:
        return "unable to write scaffold file"
    finally:
        if descriptor >= 0:
            with contextlib.suppress(OSError):
                os.close(descriptor)
        if temporary_name is not None:
            with contextlib.suppress(OSError):
                os.unlink(temporary_name, dir_fd=write.directory_fd)
    return None


def _read_bounded_bytes(
    path: Path,
    maximum_bytes: int,
    errors: list[str],
    label: str,
) -> bytes | None:
    try:
        with path.open("rb") as file:
            payload = file.read(maximum_bytes + 1)
    except FileNotFoundError:
        errors.append(f"{label} is missing")
        return None
    except OSError:
        errors.append(f"{label} is unreadable")
        return None
    if len(payload) > maximum_bytes:
        errors.append(f"{label} exceeds size limit")
        return None
    return payload


def _valid_dataset_id(value: str) -> bool:
    return value in FROZEN_DATASET_IDS and DATASET_ID_RE.fullmatch(value) is not None


def _stable_json(value: JsonObject) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True)


def _emit(payload: JsonObject, *, json_output: bool) -> None:
    if json_output:
        print(_stable_json(payload))
        return
    passed = payload.get("passed")
    if isinstance(passed, bool):
        print("PASS" if passed else "FAIL")
    else:
        print(payload.get("scope", "careerops-d0"))
    counts = payload.get("counts")
    if isinstance(counts, dict):
        for key, value in sorted(cast(dict[str, object], counts).items()):
            print(f"{key}: {value}")
    for item in cast(list[str], payload.get("created", [])):
        print(f"created: {item}")
    for item in cast(list[str], payload.get("skipped_existing", [])):
        print(f"skipped: {item}")
    errors = payload.get("errors")
    if isinstance(errors, list):
        for error in cast(list[object], errors):
            print(f"error: {error}", file=sys.stderr)


def _safe_dataset_id(value: Any) -> str:
    return value if isinstance(value, str) and value in FROZEN_DATASET_IDS else "<invalid>"


def _safe_dataset_id_or_none(value: Any) -> str | None:
    return value if isinstance(value, str) and value in FROZEN_DATASET_IDS else None


def _safe_plan_status(value: Any) -> str:
    return value if isinstance(value, str) and value in KNOWN_PLAN_STATUSES else "<invalid>"


def _non_negative_int(value: Any) -> int | None:
    if isinstance(value, int) and not isinstance(value, bool) and value >= 0:
        return value
    return None


def _reject_non_finite_json(value: str) -> None:
    raise ValueError(f"non-finite JSON number is forbidden: {value}")


def _reject_duplicate_json_keys(pairs: list[tuple[str, Any]]) -> JsonObject:
    result: JsonObject = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key is forbidden")
        result[key] = value
    return result


if __name__ == "__main__":
    raise SystemExit(main())
