#!/bin/sh
set -eu

: "${CAREEROPS_DB_RUNTIME_USER:?CAREEROPS_DB_RUNTIME_USER is required}"
: "${CAREEROPS_DB_RUNTIME_PASSWORD:?CAREEROPS_DB_RUNTIME_PASSWORD is required}"
: "${CAREEROPS_DB_WORKFLOW_USER:?CAREEROPS_DB_WORKFLOW_USER is required}"
: "${CAREEROPS_DB_WORKFLOW_PASSWORD:?CAREEROPS_DB_WORKFLOW_PASSWORD is required}"
: "${CAREEROPS_DB_MAILBOX_USER:?CAREEROPS_DB_MAILBOX_USER is required}"
: "${CAREEROPS_DB_MAILBOX_PASSWORD:?CAREEROPS_DB_MAILBOX_PASSWORD is required}"
: "${CAREEROPS_DB_MAIL_SENDER_USER:?CAREEROPS_DB_MAIL_SENDER_USER is required}"
: "${CAREEROPS_DB_MAIL_SENDER_PASSWORD:?CAREEROPS_DB_MAIL_SENDER_PASSWORD is required}"
: "${CAREEROPS_DB_GREENHOUSE_SENDER_USER:?CAREEROPS_DB_GREENHOUSE_SENDER_USER is required}"
: "${CAREEROPS_DB_GREENHOUSE_SENDER_PASSWORD:?CAREEROPS_DB_GREENHOUSE_SENDER_PASSWORD is required}"
: "${CAREEROPS_DB_OUTBOX_USER:?CAREEROPS_DB_OUTBOX_USER is required}"
: "${CAREEROPS_DB_OUTBOX_PASSWORD:?CAREEROPS_DB_OUTBOX_PASSWORD is required}"
: "${CAREEROPS_TEMPORAL_DB_USER:?CAREEROPS_TEMPORAL_DB_USER is required}"
: "${CAREEROPS_TEMPORAL_DB_PASSWORD:?CAREEROPS_TEMPORAL_DB_PASSWORD is required}"
: "${CAREEROPS_TEMPORAL_DB_NAME:?CAREEROPS_TEMPORAL_DB_NAME is required}"
: "${CAREEROPS_TEMPORAL_VISIBILITY_DB_NAME:?CAREEROPS_TEMPORAL_VISIBILITY_DB_NAME is required}"

psql --set ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname "$POSTGRES_DB" \
    --set runtime_user="$CAREEROPS_DB_RUNTIME_USER" \
    --set runtime_password="$CAREEROPS_DB_RUNTIME_PASSWORD" \
    --set workflow_user="$CAREEROPS_DB_WORKFLOW_USER" \
    --set workflow_password="$CAREEROPS_DB_WORKFLOW_PASSWORD" \
    --set mailbox_user="$CAREEROPS_DB_MAILBOX_USER" \
    --set mailbox_password="$CAREEROPS_DB_MAILBOX_PASSWORD" \
    --set mail_sender_user="$CAREEROPS_DB_MAIL_SENDER_USER" \
    --set mail_sender_password="$CAREEROPS_DB_MAIL_SENDER_PASSWORD" \
    --set greenhouse_sender_user="$CAREEROPS_DB_GREENHOUSE_SENDER_USER" \
    --set greenhouse_sender_password="$CAREEROPS_DB_GREENHOUSE_SENDER_PASSWORD" \
    --set outbox_user="$CAREEROPS_DB_OUTBOX_USER" \
    --set outbox_password="$CAREEROPS_DB_OUTBOX_PASSWORD" \
    --set temporal_user="$CAREEROPS_TEMPORAL_DB_USER" \
    --set temporal_password="$CAREEROPS_TEMPORAL_DB_PASSWORD" \
    --set temporal_db="$CAREEROPS_TEMPORAL_DB_NAME" \
    --set temporal_visibility_db="$CAREEROPS_TEMPORAL_VISIBILITY_DB_NAME" <<'SQL'
CREATE ROLE :"runtime_user"
    LOGIN PASSWORD :'runtime_password'
    NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT careerops_api TO :"runtime_user";

CREATE ROLE :"workflow_user"
    LOGIN PASSWORD :'workflow_password'
    NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT careerops_workflow TO :"workflow_user";

CREATE ROLE :"mailbox_user"
    LOGIN PASSWORD :'mailbox_password'
    NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT careerops_mailbox TO :"mailbox_user";

CREATE ROLE :"mail_sender_user"
    LOGIN PASSWORD :'mail_sender_password'
    NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT careerops_mail_sender TO :"mail_sender_user";

CREATE ROLE :"greenhouse_sender_user"
    LOGIN PASSWORD :'greenhouse_sender_password'
    NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT careerops_greenhouse_sender TO :"greenhouse_sender_user";

CREATE ROLE :"outbox_user"
    LOGIN PASSWORD :'outbox_password'
    NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT careerops_outbox TO :"outbox_user";

CREATE ROLE :"temporal_user"
    LOGIN PASSWORD :'temporal_password'
    NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE DATABASE :"temporal_db" OWNER :"temporal_user";
CREATE DATABASE :"temporal_visibility_db" OWNER :"temporal_user";
SQL
